---
- name: wget yarn repo
  get_url: url=https://dl.yarnpkg.com/rpm/yarn.repo dest=/etc/yum.repos.d/yarn.repo
  tags:
    - js 

- name: install packages
  yum: name={{ item.name }} state={{ item.state }}
  with_items:
    - { name: yarn,  state: present }
    - { name: nodejs,  state: present }
  tags:
    - js

- name: Install npm packages
  npm:
    name: webpack
    global: yes
  tags:
    - js

- name: Install YARN package manager
  package: name=yarn state=latest
  tags:
    - js
