---
- name: install packages
  yum: name={{ item.name }} state={{ item.state }}
  with_items:
    - { name: rpm-build,    state: present }
    - { name: git,          state: present }
    - { name: tig,          state: present }
    - { name: wget,         state: present }
    - { name: net-tools,    state: present }
  tags:
    - common

- name: git config name setting
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user }}"
  tags:
    - common

- name: git config email setting
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
  tags:
    - common